# multihost parameters
num_hosts: 1
server_addr: 10.1.1.3:9999
host_idx: 0

# system parameters
num: 14
dim: 3
rs: 2
T: 10000

# LCAO parameters
lcao:
  type: hf
  gamma: True
  basis: gth-dzv
  xc: lda,vwn
  rcut: 24
  grid_length: 0.5
  tol: 1e-7
  max_cycle: 100
  diis:
    diis: True
    space: 8
    start_cycle: 1
    damp: 0
  smearing: 
    smearing: True
    method: fermi
    search:
      method: newton
      cycle: 100
      tol: 1e-7
  use_jit: True
  batchsize: 512

# flow parameters
flow:
  steps: 1
  depth: 6
  h1size: 16
  h2size: 16
  Nf: 5
  remat: False

# van parameters
van:
  nlayers: 2
  modelsize: 16
  nheads: 4
  nhidden: 32
  remat: False

# wfn parameters
wfn:
  depth: 3
  h1size: 32
  h2size: 16
  Nf: 5
  remat: False

# ewald
ewald:
  Gmax: 15
  kappa: 10

# optimizer parameters
optimizer:
  flow:
    type: cg
    lr: 0.3
    decay: 0.01
    damping: 0.001
    maxnorm: 0.001
    clip_factor: 5.0
    sr:
      alpha: 0.1
    cg:
      mode: qr
      gamma: 1
      init_vec_last_step: False
      solver:
        precondition: False
        maxiter: None
        tol: 1e-10
        style: cg
  van:
    type: sr
    lr: 1
    decay: 0.01
    damping: 0.001
    maxnorm: 0.001
    clip_factor: 5.0
    sr:
      alpha: 0.1
    cg:
      mode: qr
      gamma: 1
      init_vec_last_step: False
      solver:
        precondition: False
        maxiter: None
        tol: 1e-10
        style: cg
  wfn:
    type: sr
    lr: 1
    decay: 0.01
    damping: 0.001
    maxnorm: 0.001
    clip_factor: 5.0
    sr:
      alpha: 0.1
    cg:
      mode: qr
      gamma: 1
      init_vec_last_step: False
      solver:
        precondition: False
        maxiter: None
        tol: 1e-10
        style: cg

# mc parameters
mc:
  therm: 5
  steps_p: 100
  steps_e: 800
  width_p: 0.03
  width_e: 0.07

# train parameters
batchsize: 512
acc_steps: 1
epoch: 100

# other parameters
hutchinson: False

# random seed
seed: 42

# save path
folder: /data/lizh/hydrogen/finiteT/final_hf_gth-dzv_cgqr_n20/

# load path
load:
load_pretrain:
  flow:
  van:
  wfn:

# note
note: "this is a test note."
