# multihost parameters
num_hosts: 1

# system parameters
num: 24
dim: 3
rs: 1.94
T: 10000

# PES parameters
pes:
  type: hf
  gamma: True
  basis: gth-dzv
  xc: lda,vwn
  rcut: 24
  grid_length: 0.5
  tol: 1e-7
  max_cycle: 100
  diis:
    diis: True
    space: 8
    start_cycle: 1
    damp: 0
  smearing: 
    smearing: True
    method: fermi
    search:
      method: newton
      cycle: 100
      tol: 1e-7
  use_jit: True
  Gmax: 15
  kappa: 10
  batchsize: 128

# flow parameters
flow:
  steps: 1
  depth: 6
  h1size: 16
  h2size: 16
  Nf: 5
  remat: False

# optimizer parameters
optimizer_flow: sr
lr_flow: 1.00
decay_flow: 0.01
damping_flow: 0.001
maxnorm_flow: 0.001
clip_factor: 5.0
alpha: 0.1
gamma: 1
cg:
  mode: qr
  init_vec_last_step: False
  solver:
    precondition: False
    maxiter: None
    tol: 1e-10
    style: cg

# train parameters
mc_therm: 0
mc_width_p: 0.03
mc_steps_p: 200
batchsize: 512
acc_steps: 2
epoch: 10000

# random seed
seed: 42

# save path
folder: "/data/lizh/hydrogen/finiteT/pretrain/flow/"
load: None

# note
note: "this is a test note."
